### PR TITLE
use random port rather than 5678 in case it is in use

### PR DESCRIPTION
**Pull request by bobcallaway**
Signed-off-by: Bob Callaway <bob.callaway@gmail.com>

### CODE REVIEW

**Review by lukehinds — COMMENTED** [review]
Not working unfortunately , the `server.addr` needs a `.to_s` as it complains about adding an integer and a string, but it does not seem to connect back for the return path (token) etc. I will try to debug more. BTW there is a docker-compose, but not used it yet.

**Comment by bobcallaway** [comment]
> Not working unfortunately , the `server.addr` needs a `.to_s` as it complains about adding an integer and a string, but it does not seem to connect back for the return path (token) etc. I will try to debug more. BTW there is a docker-compose, but not used it yet.

I think I have it working now... can you try again?

**Comment by lukehinds** [comment]
This works, just a question before approving: If this attempts to spawn against a random generated port number, and that port number happens to be already in use, can it handle retrying with a different port or will it abort / error out?

There is an issue with the browser message not displaying, but this is an issue in my code.

**Comment by bobcallaway** [comment]
Binding to port 0 lets the kernel select an available port from the ephemeral range. If there are no available ports, then the error path would be similar to if 5678 were in already in use with your original code.


Bob Callaway, PhD
Red Hat, Inc.
***@***.***
919.601.1526
________________________________

**Review by lukehinds — APPROVED** [review]

**Pull request merged**
