### PR TITLE
Implement gem sign

### PR DESCRIPTION
**Pull request by endorama**
Here is the ongoing implementation for `gem sign` command, following along outline from #6 

I'll keep this PR as draft to show progresses.
I'm using [`oicd_connect`](https://rubygems.org/gems/openid_connect) gem as the interface is very similar to the current `fulcio` client implementation.

### CODE REVIEW

**Comment by lukehinds** [comment]
sorry for late reply on this @endorama ,I have been trying to figure out how to get Launcy to open a browser outside of a VM.  Any ideas? I don't like installing gems on my local machine as I always end up in pain from dependency conflicts?

**Comment by endorama** [comment]
@lukehinds does it trigger an exception? (I'm having a hard time reproducing it)

My plan is to try/catch it and ignore the error if happens, while always printing the URL so it's possible to use it in other ways.

**Comment by endorama** [comment]
@lukehinds I added a `docker-compose` so everything is within it. I successfully run the command with `docker-compose run app bundle exec gem sign`.

This probably works in your VM as well, but I think your concern may be address for all contributors as well.

**Comment by endorama** [comment]
PS: I quite made a mess with my emails and GitHub, I'll fix this soon.

**Review by lukehinds — APPROVED** [review]

**Pull request merged**
