### PR TITLE
add flag to skip certain files in the boilerplate header checker

### PR DESCRIPTION
**Pull request by cpanato**
made a PR in the addlicense project to skip extensions/files and that got merged (https://github.com/google/addlicense/pull/75) see we can use here now :)

This PR adds the `-skip` flag for certain extensions/files to ignore in the boilerplate header.
for not just the extensions `yml`/`yaml`/`Gemfile`

also, remove the boilerplate for the other yamls files and Gemfile

do we need to add for others?

cc @bobcallaway @lukehinds

### CODE REVIEW

**Review by lukehinds — COMMENTED** [review]
Nice!

Couple of noted point, you have a wildcard at the end, will that skip files with no extension? It might be worth adding .md as well, for docs readme etc.

**Comment by bobcallaway** [comment]
> Nice!
> 
> Couple of noted point, you have a wildcard at the end, will that skip files with no extension? It might be worth adding .md as well, for docs readme etc.

I think the wildcard means to check all files and directories in `$CWD`, then applying the skip filter. LGTM

**Review by bobcallaway — APPROVED** [review]

**Comment by cpanato** [comment]
yes, the star was there in the first repo of sigstore that uses the addlicenses. this is to go over all directories and files from the root where you ran the command.

**Pull request merged**
