### PR TITLE
Implement call back handler and retrieve token

### PR DESCRIPTION
**Pull request by lukehinds**
Signed-off-by: Luke Hinds <lhinds@redhat.com>

### CODE REVIEW

**Comment by lukehinds** [comment]
this is a bit hacker, I am sure we might be able to handler the params better with some sort of URI modules, but for now I would like to get a prototype working.

**Review by endorama — APPROVED** [review]
Good for me, I'll work on a cleanup later on

**Comment by endorama** [comment]
I'm having some issues testing this, the login works fine but then breaks on the return callback URL.

With latest `fulcio` I get a `/ path not found`

```
fulcio-server_1        | 2021-04-20T12:57:42.669Z	ERROR	restapi/configure_fulcio_server.go:172	path / was not found	{"requestID": "514fc92083dd/oEnr3VC61K-000005"}
```

**Comment by lukehinds** [comment]
hmm, that's strange as we are not talking to fulcio yet, only the openid provider. did you add some additional code?

**Comment by endorama** [comment]
no, I run the one from this PR with latest fulcio up and running. It may be due to the callback URL? Anyway now I know this is expected, so no worries.

**Pull request merged**
